/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TravelAgency;

import business.Airline;
import business.AirlineDirectory;
import business.Flight;
import business.FlightDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class AddAirliner extends javax.swing.JPanel {

    /**
     * Creates new form CreateAirliner
     */
    private JPanel DisplayPanel;
    private AirlineDirectory airlineDirectory;
    
    public AddAirliner(JPanel dp, AirlineDirectory ad) {
        initComponents();
        DisplayPanel = dp;
        airlineDirectory = ad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextFieldName = new javax.swing.JTextField();
        OKbtn = new javax.swing.JButton();
        Cancelbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 6));
        setForeground(new java.awt.Color(153, 0, 0));
        setLayout(null);

        jLabel1.setText("Add Airliner Name: ");
        add(jLabel1);
        jLabel1.setBounds(10, 33, 130, 30);
        add(TextFieldName);
        TextFieldName.setBounds(165, 30, 200, 30);

        OKbtn.setText("OK");
        OKbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbtnActionPerformed(evt);
            }
        });
        add(OKbtn);
        OKbtn.setBounds(267, 128, 71, 23);

        Cancelbtn.setText("Cancel");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });
        add(Cancelbtn);
        Cancelbtn.setBounds(63, 128, 73, 23);

        jButton1.setText("<< back ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(60, 170, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        // TODO add your handling code here:
        //back button
           backAction();
    }//GEN-LAST:event_CancelbtnActionPerformed
 private void backAction() {
        DisplayPanel.remove(this);
        Component[] componentArray = DisplayPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirlinerJPanel manageAirlineJPanel = (ManageAirlinerJPanel) component;
        manageAirlineJPanel.refreshTable();
        CardLayout layout = (CardLayout) DisplayPanel.getLayout();
        layout.previous(DisplayPanel);
    }
    private void OKbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbtnActionPerformed
        // TODO add your handling code here:
        Airline airline = airlineDirectory.addAirline();
        airline.setFlightName(TextFieldName.getText());
        TextFieldName.setText(" ");
        JOptionPane.showMessageDialog(null, "Flight successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_OKbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JButton OKbtn;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
