/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TravelAgency;

import business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class ViewAirliner extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirliner
     */
    JPanel DisplayPanel;
    private Airline airliner;
    private Flight flight;
          
    /**
     * Creates new form ViewSupplier
     */
    public ViewAirliner(JPanel dp, Airline a) {
        initComponents();
        DisplayPanel = dp;
        airliner = a;
        
        label.setText(airliner.getFlightName());
        
        refreshTable();
        
    }
    
    private void refreshTable() {
        int rowCount = Table.getRowCount();
        DefaultTableModel model = (DefaultTableModel)Table.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Flight f : airliner.getFlightDirectory().getFlightDir()) {
            Object row[] = new Object[5];
            row[0] = f;
            row[1] = f.getFromDest();
            row[2] = f.getToDest();
            row[3] = f.getTime();
            row[4] = f.getSeats();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 6));
        setLayout(null);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "FlightNumber", "from", "To", "time", "Seats available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 510, 50);

        label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label.setText("jLabel1");
        add(label);
        label.setBounds(20, 14, 270, 40);

        jButton1.setText("<< back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(50, 200, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         DisplayPanel.remove(this);
        CardLayout layout = (CardLayout)DisplayPanel.getLayout();
        layout.previous(DisplayPanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
