/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author 123
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    private Product product;
    public ViewPanel(Product product) {
        initComponents();
        this.product = product;
        displayProduct(product);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        availNumTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        availNumTextField1 = new javax.swing.JTextField();
        descriptionTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("View Your Product");
        add(jLabel1);
        jLabel1.setBounds(175, 11, 129, 17);

        jLabel2.setText("Name:");
        add(jLabel2);
        jLabel2.setBounds(30, 70, 60, 20);

        nameTextField.setEditable(false);
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        add(nameTextField);
        nameTextField.setBounds(160, 60, 320, 30);

        jLabel3.setText("Price:");
        add(jLabel3);
        jLabel3.setBounds(30, 110, 60, 20);

        priceTextField.setEditable(false);
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });
        add(priceTextField);
        priceTextField.setBounds(160, 100, 320, 30);

        jLabel4.setText("Availabity Number:");
        add(jLabel4);
        jLabel4.setBounds(30, 150, 160, 20);

        availNumTextField.setEditable(false);
        availNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availNumTextFieldActionPerformed(evt);
            }
        });
        add(availNumTextField);
        availNumTextField.setBounds(160, 140, 320, 30);

        jLabel5.setText("Description:");
        add(jLabel5);
        jLabel5.setBounds(30, 190, 90, 20);

        descriptionTextField.setEditable(false);
        descriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextFieldActionPerformed(evt);
            }
        });
        add(descriptionTextField);
        descriptionTextField.setBounds(160, 180, 320, 30);

        jLabel6.setText("Supplier Name:");
        add(jLabel6);
        jLabel6.setBounds(30, 230, 140, 20);

        jLabel7.setText("Supplier Address: ");
        add(jLabel7);
        jLabel7.setBounds(30, 270, 130, 20);

        availNumTextField1.setEditable(false);
        availNumTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availNumTextField1ActionPerformed(evt);
            }
        });
        add(availNumTextField1);
        availNumTextField1.setBounds(160, 220, 320, 30);

        descriptionTextField1.setEditable(false);
        descriptionTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextField1ActionPerformed(evt);
            }
        });
        add(descriptionTextField1);
        descriptionTextField1.setBounds(160, 260, 320, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void availNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availNumTextFieldActionPerformed

    private void descriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTextFieldActionPerformed

    private void availNumTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availNumTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availNumTextField1ActionPerformed

    private void descriptionTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTextField1ActionPerformed
    private void displayProduct(Product product){
              
       String productName = product.getName();
       nameTextField.setText(productName);
       nameTextField.setEnabled(false);
       
       String productPrice = product.getPrice();
       priceTextField.setText(productPrice);
       priceTextField.setEnabled(false);
       
       String productAvailNum = product.getAvailNum();
       availNumTextField.setText(productAvailNum);
       availNumTextField.setEnabled(false);
       
       String productDescription = product.getDescription();
       descriptionTextField.setText(productDescription);
       descriptionTextField.setEnabled(false);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availNumTextField;
    private javax.swing.JTextField availNumTextField1;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JTextField descriptionTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField priceTextField;
    // End of variables declaration//GEN-END:variables
}
