package Interface;

import Business.Person;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Jpanelchecking extends javax.swing.JPanel {

    /**
     * Creates new form checkingaccount
     */
    private Person person;
    public Jpanelchecking(Person person) {
        initComponents();
         this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JLabel();
        Lbankname = new javax.swing.JLabel();
        TFBankname = new javax.swing.JTextField();
        TFCBankroutingno = new javax.swing.JTextField();
        Lbankroutingno = new javax.swing.JLabel();
        Lbankaccountno = new javax.swing.JLabel();
        TFCbankAccount = new javax.swing.JTextField();
        TFbankbalance = new javax.swing.JTextField();
        LAcountbal = new javax.swing.JLabel();
        LAccounttype = new javax.swing.JLabel();
        SubmitCA = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        Header.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Header.setText("Checking Account Information");
        add(Header);
        Header.setBounds(130, 10, 210, 15);

        Lbankname.setText("Bank name:");
        add(Lbankname);
        Lbankname.setBounds(40, 60, 80, 14);

        TFBankname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBanknameActionPerformed(evt);
            }
        });
        add(TFBankname);
        TFBankname.setBounds(170, 50, 260, 30);

        TFCBankroutingno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCBankroutingnoActionPerformed(evt);
            }
        });
        add(TFCBankroutingno);
        TFCBankroutingno.setBounds(170, 90, 260, 30);

        Lbankroutingno.setText("Bank routing number:");
        add(Lbankroutingno);
        Lbankroutingno.setBounds(40, 100, 130, 14);

        Lbankaccountno.setText("Bank account number:");
        add(Lbankaccountno);
        Lbankaccountno.setBounds(40, 140, 130, 20);
        add(TFCbankAccount);
        TFCbankAccount.setBounds(170, 130, 260, 30);

        TFbankbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFbankbalanceActionPerformed(evt);
            }
        });
        add(TFbankbalance);
        TFbankbalance.setBounds(170, 170, 260, 30);

        LAcountbal.setText("Account Balance:");
        add(LAcountbal);
        LAcountbal.setBounds(40, 180, 110, 14);

        LAccounttype.setText("Account type:");
        add(LAccounttype);
        LAccounttype.setBounds(40, 220, 110, 14);

        SubmitCA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SubmitCA.setText("Submit");
        SubmitCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitCAActionPerformed(evt);
            }
        });
        add(SubmitCA);
        SubmitCA.setBounds(180, 260, 90, 23);

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Checking");
        add(jRadioButton2);
        jRadioButton2.setBounds(170, 220, 110, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void TFbankbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFbankbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFbankbalanceActionPerformed

    private void SubmitCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitCAActionPerformed
        // TODO add your handling code here:
        person.getClasscheck().setCbankname(TFBankname.getText());
        person.getClasscheck().setCbankroutingnumb(TFCBankroutingno.getText());
        person.getClasscheck().setCbankaccountnumb(TFCbankAccount.getText());
        person.getClasscheck().setCbalance(TFbankbalance.getText());
        
          //Promt the user that the data successfuly created
        JOptionPane.showMessageDialog(null, "Successfully Submited");
    }//GEN-LAST:event_SubmitCAActionPerformed

    private void TFBanknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBanknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFBanknameActionPerformed

    private void TFCBankroutingnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCBankroutingnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCBankroutingnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header;
    private javax.swing.JLabel LAccounttype;
    private javax.swing.JLabel LAcountbal;
    private javax.swing.JLabel Lbankaccountno;
    private javax.swing.JLabel Lbankname;
    private javax.swing.JLabel Lbankroutingno;
    private javax.swing.JButton SubmitCA;
    private javax.swing.JTextField TFBankname;
    private javax.swing.JTextField TFCBankroutingno;
    private javax.swing.JTextField TFCbankAccount;
    private javax.swing.JTextField TFbankbalance;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
