package Interface;

import Business.Person;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class JPanelmedical extends javax.swing.JPanel {

    /**
     * Creates new form medical
     */
    private Person person;
    public JPanelmedical(Person person) {
        initComponents();
         this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Submitmedi = new javax.swing.JButton();
        TFnumber = new javax.swing.JTextField();
        TFalergy1 = new javax.swing.JTextField();
        TFalergy2 = new javax.swing.JTextField();
        TFalergy3 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        Header.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Header.setText("Medical Record");
        add(Header);
        Header.setBounds(190, 20, 109, 15);

        jLabel1.setText("Medical record number:");
        add(jLabel1);
        jLabel1.setBounds(50, 70, 150, 14);

        jLabel2.setText("Alergy1:");
        add(jLabel2);
        jLabel2.setBounds(50, 110, 100, 14);

        jLabel3.setText("Alergy2:");
        add(jLabel3);
        jLabel3.setBounds(50, 150, 130, 14);

        jLabel4.setText("Alergy3:");
        add(jLabel4);
        jLabel4.setBounds(50, 190, 120, 14);

        Submitmedi.setText("Submit");
        Submitmedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitmediActionPerformed(evt);
            }
        });
        add(Submitmedi);
        Submitmedi.setBounds(200, 230, 80, 23);
        add(TFnumber);
        TFnumber.setBounds(200, 60, 250, 30);
        add(TFalergy1);
        TFalergy1.setBounds(200, 100, 250, 30);
        add(TFalergy2);
        TFalergy2.setBounds(200, 140, 250, 30);
        add(TFalergy3);
        TFalergy3.setBounds(200, 180, 250, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitmediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitmediActionPerformed
        person.getClassmedi().setRecordnumb(TFnumber.getText());
        person.getClassmedi().setAlergy1(TFalergy1.getText());
        person.getClassmedi().setAlergy2(TFalergy2.getText());
        person.getClassmedi().setAlergy3(TFalergy3.getText());
        
          //Promt the user that the data successfuly created
        JOptionPane.showMessageDialog(null, "Successfully Submited");
    }//GEN-LAST:event_SubmitmediActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Header;
    private javax.swing.JButton Submitmedi;
    private javax.swing.JTextField TFalergy1;
    private javax.swing.JTextField TFalergy2;
    private javax.swing.JTextField TFalergy3;
    private javax.swing.JTextField TFnumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
