package Interface;

import Business.Person;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class JPnaelSavingaccount extends javax.swing.JPanel {

    /**
     * Creates new form Savingaccount
     */
    private Person person;
    public JPnaelSavingaccount(Person person) {
        initComponents();
         this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFBankname = new javax.swing.JTextField();
        TFBankroutingno = new javax.swing.JTextField();
        TFBankaccountno = new javax.swing.JTextField();
        TFBankBalance = new javax.swing.JTextField();
        submitSA = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Saving Account Information");
        add(jLabel1);
        jLabel1.setBounds(140, 10, 210, 14);

        jLabel2.setText("Bank name:");
        add(jLabel2);
        jLabel2.setBounds(40, 60, 80, 14);

        jLabel3.setText("Bank routing number:");
        add(jLabel3);
        jLabel3.setBounds(40, 100, 130, 14);

        jLabel4.setText("Bank account number:");
        add(jLabel4);
        jLabel4.setBounds(40, 140, 130, 14);

        jLabel5.setText("Account Balance:");
        add(jLabel5);
        jLabel5.setBounds(40, 180, 110, 14);

        jLabel6.setText("Account type:");
        add(jLabel6);
        jLabel6.setBounds(40, 220, 110, 14);
        add(TFBankname);
        TFBankname.setBounds(170, 50, 250, 30);
        add(TFBankroutingno);
        TFBankroutingno.setBounds(170, 90, 250, 30);
        add(TFBankaccountno);
        TFBankaccountno.setBounds(170, 130, 250, 30);

        TFBankBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBankBalanceActionPerformed(evt);
            }
        });
        add(TFBankBalance);
        TFBankBalance.setBounds(170, 170, 250, 30);

        submitSA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        submitSA.setText("Submit");
        submitSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitSAActionPerformed(evt);
            }
        });
        add(submitSA);
        submitSA.setBounds(180, 260, 71, 23);

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Saving");
        add(jRadioButton2);
        jRadioButton2.setBounds(170, 220, 140, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void TFBankBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBankBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFBankBalanceActionPerformed

    private void submitSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitSAActionPerformed
        // TODO add your handling code here:
        person.getClasssave().setSbankname(TFBankname.getText());
        person.getClasssave().setSbankroutingnumb(TFBankroutingno.getText());
        person.getClasssave().setSbankaccountnumb(TFBankaccountno.getText());
        person.getClasssave().setSbalance(TFBankBalance.getText());
        
          //Promt the user that the data successfuly created
        JOptionPane.showMessageDialog(null, "Successfully Submited");
    }//GEN-LAST:event_submitSAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFBankBalance;
    private javax.swing.JTextField TFBankaccountno;
    private javax.swing.JTextField TFBankname;
    private javax.swing.JTextField TFBankroutingno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton submitSA;
    // End of variables declaration//GEN-END:variables
}
