package Interface;
import Business.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private Person person;
    
    public MainFrame() {
        initComponents();
        person = new Person();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        displayjpanel = new javax.swing.JPanel();
        controljpanel = new javax.swing.JPanel();
        jbuttoondemographic = new javax.swing.JButton();
        JButtonReport = new javax.swing.JButton();
        jButtonaddress = new javax.swing.JButton();
        jButtonsaving = new javax.swing.JButton();
        jButtonchecking = new javax.swing.JButton();
        jButtonliscence = new javax.swing.JButton();
        jbuttonmedical = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout displayjpanelLayout = new javax.swing.GroupLayout(displayjpanel);
        displayjpanel.setLayout(displayjpanelLayout);
        displayjpanelLayout.setHorizontalGroup(
            displayjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        displayjpanelLayout.setVerticalGroup(
            displayjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        splitPanel.setRightComponent(displayjpanel);

        jbuttoondemographic.setText("Demographic");
        jbuttoondemographic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttoondemographicActionPerformed(evt);
            }
        });

        JButtonReport.setText("Report");
        JButtonReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonReportActionPerformed(evt);
            }
        });

        jButtonaddress.setText("Address");
        jButtonaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddressActionPerformed(evt);
            }
        });

        jButtonsaving.setText("Saving Account");
        jButtonsaving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsavingActionPerformed(evt);
            }
        });

        jButtonchecking.setText("Checking Account");
        jButtonchecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncheckingActionPerformed(evt);
            }
        });

        jButtonliscence.setText("Driver's Liscence");
        jButtonliscence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonliscenceActionPerformed(evt);
            }
        });

        jbuttonmedical.setText("Medical");
        jbuttonmedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonmedicalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Fill in your Details");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Personal Information");

        javax.swing.GroupLayout controljpanelLayout = new javax.swing.GroupLayout(controljpanel);
        controljpanel.setLayout(controljpanelLayout);
        controljpanelLayout.setHorizontalGroup(
            controljpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controljpanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2))
            .addGroup(controljpanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1))
            .addGroup(controljpanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jbuttoondemographic, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(controljpanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButtonaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(controljpanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButtonsaving, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(controljpanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButtonchecking, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(controljpanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButtonliscence, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(controljpanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jbuttonmedical, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(controljpanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(JButtonReport, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        controljpanelLayout.setVerticalGroup(
            controljpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controljpanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jbuttoondemographic)
                .addGap(11, 11, 11)
                .addComponent(jButtonaddress)
                .addGap(11, 11, 11)
                .addComponent(jButtonsaving)
                .addGap(11, 11, 11)
                .addComponent(jButtonchecking)
                .addGap(11, 11, 11)
                .addComponent(jButtonliscence)
                .addGap(11, 11, 11)
                .addComponent(jbuttonmedical)
                .addGap(43, 43, 43)
                .addComponent(JButtonReport))
        );

        splitPanel.setLeftComponent(controljpanel);

        getContentPane().add(splitPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttoondemographicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttoondemographicActionPerformed
        JPanelDemographic demo = new JPanelDemographic(person);
        splitPanel.setRightComponent(demo);
        
    }//GEN-LAST:event_jbuttoondemographicActionPerformed

    private void jButtonaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddressActionPerformed
       JPanelAddressi Address = new JPanelAddressi(person);
       splitPanel.setRightComponent(Address);
    }//GEN-LAST:event_jButtonaddressActionPerformed

    private void jButtonsavingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsavingActionPerformed
        JPnaelSavingaccount saving = new JPnaelSavingaccount(person);
        splitPanel.setRightComponent(saving);
    }//GEN-LAST:event_jButtonsavingActionPerformed

    private void jButtoncheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncheckingActionPerformed
        Jpanelchecking checking = new Jpanelchecking(person);
        splitPanel.setRightComponent(checking);
    }//GEN-LAST:event_jButtoncheckingActionPerformed

    private void jButtonliscenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonliscenceActionPerformed
        JPanelLiscence liscence = new JPanelLiscence(person);
        splitPanel.setRightComponent(liscence);
    }//GEN-LAST:event_jButtonliscenceActionPerformed

    private void jbuttonmedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonmedicalActionPerformed
       JPanelmedical medical = new JPanelmedical(person);
       splitPanel.setRightComponent(medical);
    }//GEN-LAST:event_jbuttonmedicalActionPerformed

    private void JButtonReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonReportActionPerformed
        NewJPanelReport report = new NewJPanelReport(person);
        splitPanel.setRightComponent(report);
    }//GEN-LAST:event_JButtonReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonReport;
    private javax.swing.JPanel controljpanel;
    private javax.swing.JPanel displayjpanel;
    private javax.swing.JButton jButtonaddress;
    private javax.swing.JButton jButtonchecking;
    private javax.swing.JButton jButtonliscence;
    private javax.swing.JButton jButtonsaving;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbuttonmedical;
    private javax.swing.JButton jbuttoondemographic;
    private javax.swing.JSplitPane splitPanel;
    // End of variables declaration//GEN-END:variables
}
