/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customers;

import business.Airline;
import business.AirlineDirectory;
import business.FlightDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class ManageCustomer extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomer
     */
    JPanel DisplayPanel;
    Airline airline;
    AirlineDirectory airlineDirectory;
    public ManageCustomer(JPanel DisplayPanel, AirlineDirectory airlineDirectory) {
        initComponents();
        this.DisplayPanel = DisplayPanel;
        this.airlineDirectory = airlineDirectory;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BookFlight = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 6));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer Portal");
        add(jLabel1);
        jLabel1.setBounds(200, 20, 186, 17);

        BookFlight.setText("Book Flights");
        BookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookFlightActionPerformed(evt);
            }
        });
        add(BookFlight);
        BookFlight.setBounds(210, 140, 110, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void BookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookFlightActionPerformed
        // TODO add your handling code here:
        SearchPanel search = new SearchPanel(DisplayPanel,airlineDirectory);
        DisplayPanel.add("SEARCH FLIGHTS",search);
        CardLayout layout = (CardLayout)DisplayPanel.getLayout();
        layout.next(DisplayPanel);
    }//GEN-LAST:event_BookFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookFlight;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
