/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customers;

import business.Customer;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */

public class SeatSelect extends javax.swing.JPanel {

    /**
     * Creates new form SeatSelect
     */
    JPanel DisplayPanel;
    Customer customer;
    public SeatSelect(JPanel DisplayPanel, Customer customer) {
        initComponents();
        this.DisplayPanel = DisplayPanel;
        this.customer = customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldFname = new javax.swing.JTextField();
        textfieldLname = new javax.swing.JTextField();
        textfieldPNum = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 6));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Passenger Details:");
        add(jLabel1);
        jLabel1.setBounds(32, 36, 203, 27);

        jLabel2.setText("First Name:");
        add(jLabel2);
        jLabel2.setBounds(32, 84, 150, 20);

        jLabel3.setText("Last Name:");
        add(jLabel3);
        jLabel3.setBounds(32, 119, 150, 20);

        jLabel4.setText("Passport Number:");
        add(jLabel4);
        jLabel4.setBounds(32, 157, 150, 20);
        add(textFieldFname);
        textFieldFname.setBounds(203, 81, 180, 30);
        add(textfieldLname);
        textfieldLname.setBounds(203, 116, 180, 30);
        add(textfieldPNum);
        textfieldPNum.setBounds(203, 154, 180, 30);

        jButton1.setText("Confirm Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(210, 330, 150, 30);

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(30, 330, 90, 23);

        jLabel5.setText("Airline Name:");
        add(jLabel5);
        jLabel5.setBounds(40, 210, 110, 30);

        jLabel6.setText("Flight Name:");
        add(jLabel6);
        jLabel6.setBounds(40, 250, 90, 20);

        jLabel7.setText("To:");
        add(jLabel7);
        jLabel7.setBounds(330, 290, 70, 20);

        jLabel8.setText("From:");
        add(jLabel8);
        jLabel8.setBounds(40, 290, 70, 20);

        jLabel9.setText("jLabel9");
        add(jLabel9);
        jLabel9.setBounds(200, 250, 200, 20);

        jLabel10.setText("jLabel9");
        add(jLabel10);
        jLabel10.setBounds(380, 290, 110, 20);

        jLabel11.setText("jLabel9");
        add(jLabel11);
        jLabel11.setBounds(200, 220, 200, 20);

        jLabel12.setText("jLabel9");
        add(jLabel12);
        jLabel12.setBounds(200, 290, 110, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Customer cstm = customer.getCustomerDirectory().addCustomer();
           cstm.setFname(textFieldFname.getText());
           cstm.setLname(textfieldLname.getText());
           cstm.setPassportNumber(textfieldPNum.getText());
                   //fly.setTime(textfiledTime.getText());
           JOptionPane.showMessageDialog(null, "Flight successfully Booked", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DisplayPanel.remove(this);
        CardLayout layout = (CardLayout)DisplayPanel.getLayout();
        layout.previous(DisplayPanel);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textFieldFname;
    private javax.swing.JTextField textfieldLname;
    private javax.swing.JTextField textfieldPNum;
    // End of variables declaration//GEN-END:variables
}
