/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customers;

import business.Airline;
import business.Customer;
import business.Flight;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class SeatSelect extends javax.swing.JPanel {

    /**
     * Creates new form SeatSelect
     */
    JPanel DisplayPanel;
    Customer customer;
    Flight flight;
    Airline airline;

    public SeatSelect(JPanel DisplayPanel, Customer customer, Flight flight) {
        initComponents();
        this.DisplayPanel = DisplayPanel;
        this.flight = flight;
        customer = new Customer();
        this.customer = customer;
        
        textfieldseat.setText(String.valueOf(flight.getSeats()));
       //nameLable.setText(airline.getFlightName());
        fnameLable.setText(flight.getFilghtName());
        fromLable.setText(flight.getFromDest());
        tolable.setText(flight.getToDest());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldFname = new javax.swing.JTextField();
        textfieldLname = new javax.swing.JTextField();
        textfieldPNum = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fnameLable = new javax.swing.JLabel();
        tolable = new javax.swing.JLabel();
        fromLable = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textfieldseat = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 6));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Passenger Details:");
        add(jLabel1);
        jLabel1.setBounds(32, 36, 203, 27);

        jLabel2.setText("First Name:");
        add(jLabel2);
        jLabel2.setBounds(32, 84, 150, 20);

        jLabel3.setText("Last Name:");
        add(jLabel3);
        jLabel3.setBounds(32, 119, 150, 20);

        jLabel4.setText("Passport Number:");
        add(jLabel4);
        jLabel4.setBounds(32, 157, 150, 20);
        add(textFieldFname);
        textFieldFname.setBounds(203, 81, 180, 30);
        add(textfieldLname);
        textfieldLname.setBounds(203, 116, 180, 30);
        add(textfieldPNum);
        textfieldPNum.setBounds(203, 154, 180, 30);

        jButton1.setText("Confirm Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(270, 360, 150, 30);

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(80, 370, 90, 23);

        jLabel6.setText("Flight Name:");
        add(jLabel6);
        jLabel6.setBounds(30, 280, 90, 20);

        jLabel7.setText("To:");
        add(jLabel7);
        jLabel7.setBounds(320, 320, 40, 20);

        jLabel8.setText("From:");
        add(jLabel8);
        jLabel8.setBounds(30, 320, 70, 20);
        add(fnameLable);
        fnameLable.setBounds(190, 280, 200, 20);
        add(tolable);
        tolable.setBounds(370, 320, 110, 20);
        add(fromLable);
        fromLable.setBounds(190, 320, 110, 20);

        jLabel13.setText("Seat:");
        add(jLabel13);
        jLabel13.setBounds(30, 210, 70, 20);

        textfieldseat.setEditable(false);
        add(textfieldseat);
        textfieldseat.setBounds(200, 200, 180, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (flight.getSeats() > 0) {
            
            Customer cstm = customer.getCustomerDirectory().addCustomer();
            cstm.setFname(textFieldFname.getText());
            cstm.setLname(textfieldLname.getText());
            cstm.setPassportNumber(textfieldPNum.getText());
            //fly.setTime(textfiledTime.getText());
            flight.seatdecrease();
            JOptionPane.showMessageDialog(null, "Flight successfully Booked", "Warning", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Sorry no seats Available \n try back later", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DisplayPanel.remove(this);
        CardLayout layout = (CardLayout) DisplayPanel.getLayout();
        layout.previous(DisplayPanel);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fnameLable;
    private javax.swing.JLabel fromLable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textFieldFname;
    private javax.swing.JTextField textfieldLname;
    private javax.swing.JTextField textfieldPNum;
    private javax.swing.JTextField textfieldseat;
    private javax.swing.JLabel tolable;
    // End of variables declaration//GEN-END:variables
}
