/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.*;
import javax.swing.JOptionPane;


/**
 *
 * @author hp
 */
public class Create extends javax.swing.JPanel {

    /**
     * Creates new form Create
     */
   
    private VitalSignsHistory vsh;  //global variable
public Create(VitalSignsHistory vsh) {  //Local variable vsh
         initComponents();
        this.vsh = vsh; //assigning global variable to local variable // this <global variable> = <local variable>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lableTemperature = new javax.swing.JLabel();
        lableBP = new javax.swing.JLabel();
        lablePulse = new javax.swing.JLabel();
        lableDate = new javax.swing.JLabel();
        bttonCreate = new javax.swing.JButton();
        textFieldTemperature = new javax.swing.JTextField();
        textFileldPulse = new javax.swing.JTextField();
        textFieldDate = new javax.swing.JTextField();
        textFieldBP = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Create Vital Sign");
        add(jLabel1);
        jLabel1.setBounds(200, 10, 250, 60);

        lableTemperature.setText("Temperature:");
        add(lableTemperature);
        lableTemperature.setBounds(40, 110, 120, 20);

        lableBP.setText("Blood Pressure:");
        add(lableBP);
        lableBP.setBounds(40, 160, 130, 20);

        lablePulse.setText("Pulse:");
        add(lablePulse);
        lablePulse.setBounds(40, 220, 80, 20);

        lableDate.setText("Date:");
        add(lableDate);
        lableDate.setBounds(40, 280, 80, 20);

        bttonCreate.setText("Create");
        bttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttonCreateActionPerformed(evt);
            }
        });
        add(bttonCreate);
        bttonCreate.setBounds(230, 330, 80, 40);
        add(textFieldTemperature);
        textFieldTemperature.setBounds(180, 100, 220, 30);

        textFileldPulse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFileldPulseActionPerformed(evt);
            }
        });
        add(textFileldPulse);
        textFileldPulse.setBounds(180, 210, 220, 30);
        add(textFieldDate);
        textFieldDate.setBounds(180, 270, 220, 30);
        add(textFieldBP);
        textFieldBP.setBounds(180, 150, 220, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void textFileldPulseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFileldPulseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFileldPulseActionPerformed

    private void bttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttonCreateActionPerformed
        // TODO add your handling code here:
        //Storing TextField Vlues into the Local Vriable
        double temperature = Double.parseDouble(textFieldTemperature.getText());
        double bp  = Double.parseDouble(textFieldBP.getText());
        int pulse = Integer.parseInt(textFileldPulse.getText());
        String date = textFieldDate.getText();
        VitalSigns v = vsh.addVitals();
        v.setTemperature(temperature);
        v.setBloodPressure(bp);
        v.setPulse(pulse);
        v.setDate(date);
        
      
        JOptionPane.showMessageDialog(null, "Successfully Added");
        textFieldTemperature.setText(" ");
        textFieldBP.setText(" ");
        textFileldPulse.setText(" ");
        textFieldDate.setText(" ");
    }//GEN-LAST:event_bttonCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttonCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lableBP;
    private javax.swing.JLabel lableDate;
    private javax.swing.JLabel lablePulse;
    private javax.swing.JLabel lableTemperature;
    private javax.swing.JTextField textFieldBP;
    private javax.swing.JTextField textFieldDate;
    private javax.swing.JTextField textFieldTemperature;
    private javax.swing.JTextField textFileldPulse;
    // End of variables declaration//GEN-END:variables
}
