/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignsHistory;

/**
 *
 * @author hp
 */
public class MianFrame extends javax.swing.JFrame {

    /**
     * Creates new form MianFrame
     */
    
    private VitalSignsHistory vsh;  //declaration
    
    public MianFrame() {
        initComponents();  //internally generated, creates all view the components
        
        this.vsh = new VitalSignsHistory();  //Initialization
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        displayPanel = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        bttonCreate = new javax.swing.JButton();
        bttonView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textfieldMax = new javax.swing.JTextField();
        textFiledMin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 492));

        SplitPane.setBackground(new java.awt.Color(255, 255, 255));
        SplitPane.setDividerLocation(180);
        SplitPane.setName(""); // NOI18N
        SplitPane.setPreferredSize(new java.awt.Dimension(1500, 470));

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(displayPanel);

        controlPanel.setLayout(null);

        bttonCreate.setText("Create Vital Signs");
        bttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttonCreateActionPerformed(evt);
            }
        });
        controlPanel.add(bttonCreate);
        bttonCreate.setBounds(10, 70, 130, 30);

        bttonView.setText("View Vital Signs ");
        bttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttonViewActionPerformed(evt);
            }
        });
        controlPanel.add(bttonView);
        bttonView.setBounds(10, 150, 130, 30);

        jLabel1.setText("Max_Pulse:");
        controlPanel.add(jLabel1);
        jLabel1.setBounds(20, 224, 80, 20);

        jLabel2.setText("Min_Pulse:");
        controlPanel.add(jLabel2);
        jLabel2.setBounds(20, 274, 80, 20);

        textfieldMax.setEditable(false);
        textfieldMax.setText("70");
        controlPanel.add(textfieldMax);
        textfieldMax.setBounds(90, 220, 70, 30);

        textFiledMin.setEditable(false);
        textFiledMin.setText("35");
        controlPanel.add(textFiledMin);
        textFiledMin.setBounds(90, 270, 70, 30);

        jButton1.setText("Abnormal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        controlPanel.add(jButton1);
        jButton1.setBounds(40, 330, 90, 40);

        SplitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttonCreateActionPerformed
        // TODO add your handling code here:
        Create create = new Create(vsh);
        SplitPane.setRightComponent(create);
    }//GEN-LAST:event_bttonCreateActionPerformed

    private void bttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttonViewActionPerformed
        // TODO add your handling code here:
       View view = new View(vsh);
        SplitPane.setRightComponent(view);
    }//GEN-LAST:event_bttonViewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String maxbpString = textfieldMax.getText();
        String minbpString = textFiledMin.getText();
        double maxbp =  maxbpString.equals("")? Double.MAX_VALUE : Double.parseDouble(maxbpString);
        double minbp =  minbpString.equals("")? Double.MIN_VALUE : Double.parseDouble(minbpString);
        AbnormalPanel  abnormalpanel = new AbnormalPanel(vsh,maxbp,minbp);
        SplitPane.setRightComponent(abnormalpanel);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**s
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MianFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton bttonCreate;
    private javax.swing.JButton bttonView;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textFiledMin;
    private javax.swing.JTextField textfieldMax;
    // End of variables declaration//GEN-END:variables
}
