/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Interface.Customers.ManageCustomer;
import Interface.ManageAirliner.AirlinerLogin;
import Interface.TravelAgency.ManageAirlinerJPanel;
import business.*;
import java.awt.CardLayout;

/**
 *
 * @author hp
 */

public class MainFrame extends javax.swing.JFrame {
private AirlineDirectory airlineDirectory;
private FlightDirectory flightDirectory;
Airline airline;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        airlineDirectory = new AirlineDirectory();
        //flightDirectory = new FlightDirectory();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        Airlinerbtn = new javax.swing.JButton();
        TravelAgencybtn = new javax.swing.JButton();
        Customerbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DisplayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPane.setDividerLocation(150);
        SplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        SplitPane.setPreferredSize(new java.awt.Dimension(6000, 3000));

        ControlPanel.setBackground(new java.awt.Color(153, 0, 0));
        ControlPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 6));

        Airlinerbtn.setText("Airliner");
        Airlinerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirlinerbtnActionPerformed(evt);
            }
        });

        TravelAgencybtn.setText("Travel Agency");
        TravelAgencybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TravelAgencybtnActionPerformed(evt);
            }
        });

        Customerbtn.setText("Customer");
        Customerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Welcome to Management Center for Travel Agency, Airliner and Customers");

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TravelAgencybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Airlinerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Customerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(5038, Short.MAX_VALUE))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Airlinerbtn)
                    .addComponent(Customerbtn)
                    .addComponent(TravelAgencybtn)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(ControlPanel);

        DisplayPanel.setLayout(new java.awt.CardLayout());
        SplitPane.setRightComponent(DisplayPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TravelAgencybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TravelAgencybtnActionPerformed
        // TODO add your handling code here:
        //Manages Supplier
        ManageAirlinerJPanel map = new ManageAirlinerJPanel(DisplayPanel, airlineDirectory);
        DisplayPanel.add("ManageAirline",map);
        CardLayout layout = (CardLayout)DisplayPanel.getLayout();
        layout.next(DisplayPanel);
    }//GEN-LAST:event_TravelAgencybtnActionPerformed

    private void AirlinerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirlinerbtnActionPerformed
        // TODO add your handling code here:
        //manages schedules 
        AirlinerLogin al = new AirlinerLogin(DisplayPanel,airlineDirectory);
        DisplayPanel.add("LoginAirlineJPanel",al);
        CardLayout layout = (CardLayout)DisplayPanel.getLayout();
        layout.next(DisplayPanel);
    }//GEN-LAST:event_AirlinerbtnActionPerformed

    private void CustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerbtnActionPerformed
        // TODO add your handling code here:
        //search
        ManageCustomer cus = new ManageCustomer(DisplayPanel, airlineDirectory);
        DisplayPanel.add("LoginAirlineJPanel",cus);
        CardLayout layout = (CardLayout)DisplayPanel.getLayout();
        layout.next(DisplayPanel);
    }//GEN-LAST:event_CustomerbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Airlinerbtn;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JButton Customerbtn;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton TravelAgencybtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
